In [1]:

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
from pathlib import Path 
import sys 
import os 
import logging
import seaborn as sns
from decimal import Decimal, ROUND_DOWN

from scipy.stats import uniform, randint
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV, GroupShuffleSplit
from sklearn.metrics import make_scorer ,root_mean_squared_error

from collections import Counter
from sklearn.preprocessing import FunctionTransformer, StandardScaler

from helper.transformers import CorrelationSelector,PreserveFeatureNames, LeastDistanceCorrelatedRandomFeature


from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import GroupKFold,  cross_validate
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor 
from lightgbm import LGBMRegressor
from sklearn.svm import SVR

from sklearn.compose import TransformedTargetRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from skrub import TableVectorizer


from sklearn.model_selection import cross_val_score
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, accuracy_score, classification_report, confusion_matrix

sys.path.append('/Users/alina/Desktop/MIT/code/ADHD/MTA/helper')
from helper import rr, prep, var_dict, audit, plot, save, ml


%load_ext autoreload
%autoreload 2

#shap.initjs()

In [2]:
if Path('/Volumes/Samsung_T5/MIT/mta').exists():
    data_root =     '/Volumes/Samsung_T5/MIT/mta'
    data_derived  = '/Volumes/Samsung_T5/MIT/mta/output/derived_data'
else: 
    data_root = '/Users/alina/Desktop/MIT/code/data'
    data_derived  = '/Users/alina/Desktop/MIT/code/data/output/derived_data'

info_path = Path(data_root, "files")
types_file_path = Path(data_derived,"all_vars_description_ML.xlsx" )
#os.listdir(data_derived)


In [3]:
################## PREDICTORS ####################
pred = pd.read_csv(Path(data_derived, 'mta_data_clean.csv')).drop(columns = 'Unnamed: 0')
out = pd.read_csv(Path(data_derived, 'out_clean_all_raters.csv')).drop(columns = 'Unnamed: 0')


rater_out = 'm'
rater_pred = "m"

thr_drop_missing = 50 # if changed to lower number, some cols will be dropped, 50 iwas threshold in preprcessing (wont change anything)

model_type = "RF"
corr_select= False # use correlation selector or not 




In [4]:
outcome_short = "ODD"
file_name_save = 'results_ML_simple_CV_RF_XGB_{}.csv'.format(outcome_short)
file_path_save = Path(data_derived, 'ML_results', file_name_save)

In [5]:
out_dict = {"HYP": 'snap_snahypat', "INATT": 'snap_snainatt', "ODD": 'snap_snaoddt', 'SS': 'ssrs_ssptosst', "INTERN": 'ssrs_sspintt', "DOM" : 'pcrc_pcrcpax', 'INTIM': 'pcrc_pcrcprx'}
outcome_result_dict = {'ODD':  "SNAP ODD Symptoms T Score", "HYP": "SNAP Hyperactivity Symptoms T Score", "INATT" :"SNAP Inattention Symptoms T Score" , "INTERN": "SSRS Internalizing Symptoms", "SS": "SSRS Social Skills T Score", "DOM": "Parental Dominance Mean Score", "INTIM": "Parent-Child Intimacy Mean Score"}
outcome_var = out_dict[outcome_short]
outcome_var

'snap_snaoddt'

In [6]:
data, df_X, y, rater_count_X = ml.prepare_data(pred, out, rater_pred, rater_out, thr_drop_missing, outcome_var)


Preparing data...
Index([], dtype='object')
Removing empty columns ..  N =  0
Index([], dtype='object')
(559, 348)
Removing constant columns .. N =  0
Index([], dtype='object')
(559, 348)
Removing known and raw columns..  N =  : 0
[]
(559, 348)
Removing above threshold empty columns.. N =  : 0
set()
(559, 348)

Outcome to predict (Y) :  snap_snaoddt_m_out

Y shape:  (503,)
X shape  (503, 346)
Columns ending with 'm': 277
Columns ending with 'f': 0
Columns ending with 'c': 68
Columns ending with 't': 0


In [7]:
ml.check_duplicates(df_X)


Checking for duplicates...
Duplicated column names: []


[]

In [8]:

ord_vars, num_vars, cat_vars_str, cat_vars_num = ml.get_var_types(df_X, types_file_path)



Extracting variable types from file...

Ordinal variables: 367
Numeric variables: 66
Categorical numeric variables: 12
Categorical string variables: 3

 Checking for overlaps.. 
Overlap between num_vars and ord_vars: set()
Overlap between num_vars and cat_vars_str: set()
Overlap between num_vars and cat_vars_num: set()
Overlap between ord_vars and cat_vars_str: set()
Overlap between ord_vars and cat_vars_num: set()
Overlap between cat_vars_str and cat_vars_num: set()
Overlap across all lists: set()


In [9]:

scoring = {
    'r2': 'r2',
    'mse': 'neg_mean_squared_error',
    'mae': 'neg_mean_absolute_error'
}

groups = data['src_subject_id'].values

## Next   Compute 
- simple model results for XG boost , finish for RF
- accuracy as correlation prediction - label ? 
- add cross validation loop  
- feature importances in cross validation 
- split half reliabiliy of feature importances across splits 
- reliability of feature importances across models 

In [10]:
X_ord = df_X[ord_vars]
X_ord.shape

(503, 367)

In [11]:
ordinal_encoder = OrdinalEncoder()
test = ordinal_encoder.fit_transform(X_ord)
test.shape

(503, 367)

In [12]:
test2 = np.array(X_ord)

In [13]:
xx = [pd.DataFrame(test)[col].unique() for col in pd.DataFrame(test).columns]
xx

[array([ 0.,  3.,  1.,  2., nan]),
 array([ 0., nan,  2.,  1.,  3.]),
 array([ 1., nan,  3.,  0.,  2.]),
 array([ 0.,  3.,  1.,  2., nan]),
 array([ 2.,  3.,  0.,  1., nan]),
 array([ 2.,  3.,  0.,  1., nan]),
 array([ 2.,  3.,  1., nan,  0.]),
 array([ 1., nan,  2.,  0.,  3.]),
 array([ 1.,  3.,  2., nan,  0.]),
 array([ 1.,  2.,  3.,  0., nan]),
 array([ 0.,  3.,  2.,  1., nan]),
 array([ 1.,  3.,  2., nan,  0.]),
 array([ 1.,  3.,  2., nan,  0.]),
 array([ 2.,  3.,  1., nan,  0.]),
 array([ 2.,  1.,  3., nan,  0.]),
 array([ 1.,  3.,  2.,  0., nan]),
 array([ 2.,  3.,  1., nan,  0.]),
 array([ 1.,  3.,  2., nan,  0.]),
 array([ 1.,  2.,  0.,  3., nan]),
 array([ 0., nan,  1.,  3.,  2.]),
 array([ 0., nan,  1.,  2.,  3.]),
 array([ 1.,  2.,  3., nan,  0.]),
 array([ 1.,  3.,  0.,  2., nan]),
 array([ 1.,  3.,  2., nan,  0.]),
 array([ 0.,  3.,  2.,  1., nan]),
 array([ 1., nan,  3.,  2.,  0.]),
 array([ 0.,  3.,  2.,  1., nan]),
 array([ 0.,  3.,  2.,  1., nan]),
 array([ 2.,  3.,  1

In [14]:
ohe = OneHotEncoder()
test_ohe = ohe.fit_transform(X_ord)

In [15]:
test_ohe.shape

(503, 1799)

In [16]:
for val in test[test != test2]:
    print(val)

1.0
2.0
4.0
3.0
2.0
2.0
3.0
1.0
3.0
3.0
3.0
2.0
2.0
3.0
1.0
2.0
2.0
3.0
2.0
2.0
6.0
4.0
4.0
6.0
6.0
4.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
2.0
1.0
2.0
2.0
2.0
4.0
2.0
2.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
1.0
0.0
1.0
1.0
0.0
0.0
2.0
0.0
0.0
0.0
1.0
0.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.0
2.0
3.0
2.0
3.0
3.0
3.0
4.0
3.0
2.0
1.0
3.0
1.0
3.0
1.0
2.0
4.0
3.0
2.0
2.0
3.0
1.0
3.0
3.0
3.0
3.0
2.0
2.0
3.0
1.0
2.0
2.0
3.0
2.0
3.0
2.0
2.0
2.0
3.0
3.0
2.0
3.0
2.0
3.0
3.0
3.0
4.0
3.0
2.0
1.0
3.0
3.0
nan
nan
nan
nan
nan
nan
nan
3.0
2.0
3.0
3.0
2.0
1.0
3.0
3.0
1.0
3.0
3.0
2.0
2.0
3.0
2.0
3.0
2.0
2.0
3.0
4.0
9.0
9.0
7.0
9.0
0.0
4.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.0
2.0
2.0
2.0
2.0
1.0
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.0
0.0
1.0
2.0
1.0
2.0
3.0
2.0
2.0
3.0
3.0
4.0
2.0
3.0
2.0
3.0
3.0
2.0
1.0
3.0
3.0
1.0
3.0
3.0
3.0
2.0
2.0
3.0
2.0
3.0
2.0
2.0
3.0
2.0
4.0


In [17]:
imp =  PreserveFeatureNames(SimpleImputer(strategy='constant', fill_value=-1)) # change that to OrdinalEncoder sklearn -- just encodes to catgoreies !!
ordinal_encoder =  PreserveFeatureNames(OrdinalEncoder())

In [18]:
X_ord_imp = imp.fit_transform(X_ord)
X_ord_enc = ordinal_encoder.fit_transform(X_ord_imp)

In [19]:
np.isnan(X_ord_enc).any()

False

In [20]:
test = LeastDistanceCorrelatedRandomFeature()

In [21]:
import warnings
warnings.filterwarnings("ignore")

if model_type == "XGB":
    regress =  XGBRegressor(random_state=42)
elif model_type == "RF":
    regress = RandomForestRegressor(random_state= 42)


num_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')), # check paper 
    ('std_scaler',StandardScaler())
])

ord_pipe = Pipeline([
    ('imputer', PreserveFeatureNames(SimpleImputer(strategy='constant', fill_value=-1))), # change that to OrdinalEncoder sklearn -- just encodes to catgoreies !!
    ('identity', PreserveFeatureNames(OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)))
])


cat_str_pipe = Pipeline([
    ('imputer', PreserveFeatureNames(SimpleImputer(strategy='constant', fill_value='missing'))),
     ('ohe', PreserveFeatureNames(TableVectorizer()))
])

cat_num_pipe = Pipeline([
    ('imputer', PreserveFeatureNames(SimpleImputer(strategy='constant', fill_value=-1))),
    ('ohe', PreserveFeatureNames(OneHotEncoder(handle_unknown="ignore")))
])

preprocessor = ColumnTransformer([
    ('num', num_pipe, num_vars),
    ('cat_str', cat_str_pipe, cat_vars_str),
    ('cat_num', cat_num_pipe, cat_vars_num),
    ('ord', ord_pipe, ord_vars)
])

if corr_select : 
    pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('correlation_selector', CorrelationSelector(threshold=0.8)),
    ('rand_feature',  LeastDistanceCorrelatedRandomFeature(n_candidates=10, random_state=42, feature_name = "random_vector")),
    ('regressor',regress)
    ])
else: 
    pipeline = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('rand_feature', LeastDistanceCorrelatedRandomFeature(n_candidates=10, random_state=42, feature_name = "random_vector")),
        ('regressor',regress)
    ])

if model_type == "RF":
    param_distributions = {
        'regressor__n_estimators': [100, 300],          # Correct prefix
        'regressor__max_depth': [10, None],
        'regressor__min_samples_split': [2, 10],
        'regressor__min_samples_leaf': [1, 4]
    }
    
elif model_type == "XGB":
    param_distributions = {
        'regressor__n_estimators': [100, 300],
        'regressor__max_depth': [10],                    # Removed None
        'regressor__colsample_bytree': [0.5, 0.3],       # Mapped 'sqrt' and 'log2' to numeric values
        'regressor__min_child_weight': [2, 10, 1, 4],    # Combined 'min_samples_split' and 'min_samples_leaf'
    }
    
# Define the parameter grid

# Define the GroupKFold cross-validation
cv = GroupKFold(n_splits=5)

# Define the scorer
scorer = {
    'rmse': make_scorer(root_mean_squared_error, greater_is_better=False),
    'mae': make_scorer(mean_absolute_error, greater_is_better=False),
    'r2': make_scorer(r2_score)
}

# Set up the RandomizedSearchCV
random_search = RandomizedSearchCV(
    estimator=pipeline,
    param_distributions=param_distributions,
    n_iter=3,  # Number of parameter settings to sample
    scoring=scorer,
    refit='rmse', 
    cv=cv,
    verbose=3,
    random_state=42
)

# Perform the search
random_search.fit(df_X, y, groups=groups)

# Print best parameters and score
print("Best Parameters:", random_search.best_params_)
print("Best Score:", random_search.best_score_)

#pipeline.fit(X_train_val, y_train_val)

Fitting 5 folds for each of 3 candidates, totalling 15 fits
0.1127635144640854
[CV 1/5] END regressor__max_depth=10, regressor__min_samples_leaf=1, regressor__min_samples_split=2, regressor__n_estimators=100; mae: (test=-3.939) r2: (test=0.252) rmse: (test=-5.012) total time=   1.8s
0.10238663967007541
[CV 2/5] END regressor__max_depth=10, regressor__min_samples_leaf=1, regressor__min_samples_split=2, regressor__n_estimators=100; mae: (test=-3.736) r2: (test=0.323) rmse: (test=-4.812) total time=   1.7s
0.11305360429550787
[CV 3/5] END regressor__max_depth=10, regressor__min_samples_leaf=1, regressor__min_samples_split=2, regressor__n_estimators=100; mae: (test=-3.348) r2: (test=0.385) rmse: (test=-4.213) total time=   1.7s
0.06713690787291017
[CV 4/5] END regressor__max_depth=10, regressor__min_samples_leaf=1, regressor__min_samples_split=2, regressor__n_estimators=100; mae: (test=-3.753) r2: (test=0.286) rmse: (test=-4.887) total time=   1.8s
0.07062213094383626
[CV 5/5] END regresso

In [22]:
random_search.best_score_


-4.708827379282527

In [23]:
# best_pipeline = random_search.best_estimator_

# # 1) Get the list of final feature names from CorrelationSelector
# selector = best_pipeline.named_steps['correlation_selector']
# final_feature_names = selector.get_support(indices=False)  # returns the column names it kept

# # 2) Get the trained regressor and its feature importances
# final_model = best_pipeline.named_steps['regressor']
# importances = final_model.feature_importances_

# # 3) Pair up each feature name with its importance
# import pandas as pd

# feature_importance_df = pd.DataFrame({
#     'feature': final_feature_names,
#     'importance': importances
# }).sort_values(by='importance', ascending=False)

# print("\nFeature Importances:")
# print(feature_importance_df)

In [24]:
# Assuming feat_imp_df is your DataFrame with 'feature' and 'importance' columns
# feat_imp_df = pd.DataFrame({
#     'feature': final_feature_names,
#     'importance': importances
# }).sort_values(by='importance', ascending=False)

# Plot the top 20 features
# top_n = 20
# top_features = feature_importance_df.head(top_n).sort_values(by='importance')

# plt.figure(figsize=(10, 8))
# plt.barh(top_features['feature'], top_features['importance'], color='skyblue')
# plt.xlabel('Feature Importance')
# plt.title(f'Top {top_n} Feature Importances')
# plt.tight_layout()
# plt.show()

In [25]:
# y_pred = random_search.predict(X_test)
# # Calculate evaluation metrics
# mse = mean_squared_error(y_test, y_pred)
# rmse = np.sqrt(mse)
# mae = mean_absolute_error(y_test, y_pred)
# r2 = r2_score(y_test, y_pred)

# print(f"Mean Squared Error: {mse}")
# print(f"Root Mean Squared Error: {rmse}")
# print(f"Mean Absolute Error: {mae}")
# print(f"R^2 Score: {r2}")


# feature importances and plot raondm vector index 

In [26]:
def truncate(value, decimals):
    value = Decimal(value)
    return float(value.quantize(Decimal(f"1.{'0' * decimals}"), rounding=ROUND_DOWN))


In [27]:
outcome_var_table = "{} ({})".format(outcome_result_dict[outcome_short], rater_out.upper())
outcome_var_table

'SNAP ODD Symptoms T Score (M)'

In [28]:
random_search.best_estimator_.named_steps.keys()

dict_keys(['preprocessor', 'rand_feature', 'regressor'])

- for r2 reuslts--> no need for center of mass approach 
- center of mass for feature importances (= rank sum vote?) 

In [29]:
new_row = ml.get_results_from_random_search(random_search, outcome_short, rater_out= rater_out,  rater_pred=rater_pred,thr_drop_missing= thr_drop_missing, get_dist=True)
new_row

{'m': 43, 'f': 0, 'c': 24, 't': 0}
Metrics for Best Parameters:
mean_test_rmse   -4.708827
mean_test_mae    -3.713467
mean_test_r2      0.304788
Name: 2, dtype: object


{'Model Name': 'RandomForestRegressor',
 'Cross Validation Type': 'GroupKFold(n_splits=5)',
 'Hyperparameters': 'n_estimators: 300\nmin_samples_split: 2\nmin_samples_leaf: 4\nmax_depth: 10',
 'Mean Squared Error Distribution': [25.099221575975037,
  23.564779632763408,
  17.448099929807803,
  24.12466387908855,
  21.078098707293044],
 'Root Mean Squared Error Distribution': [-5.0099123321646095,
  -4.854356768178809,
  -4.17709228169642,
  -4.911686459770061,
  -4.591089054602736],
 'Mean Absolute Error Distribution': [-3.9206284072272664,
  -3.7924721709774807,
  -3.277684058995251,
  -3.786044304345365,
  -3.7905073858197182],
 'R² Score Distribution': [0.252690625849295,
  0.31061029356432945,
  0.3954907810104491,
  0.2789921824718288,
  0.2861536294202679],
 'Outcome Variable': 'SNAP ODD Symptoms T Score\n- rated  by Mother',
 'Number of Features': 'Selection : Mother \n Total: 502\nMother: 43\nFather: 0\nTeacher: 0\nChild: 24',
 'Feature Selection Method': 'No feature selection',

In [30]:
new_row

{'Model Name': 'RandomForestRegressor',
 'Cross Validation Type': 'GroupKFold(n_splits=5)',
 'Hyperparameters': 'n_estimators: 300\nmin_samples_split: 2\nmin_samples_leaf: 4\nmax_depth: 10',
 'Mean Squared Error Distribution': [25.099221575975037,
  23.564779632763408,
  17.448099929807803,
  24.12466387908855,
  21.078098707293044],
 'Root Mean Squared Error Distribution': [-5.0099123321646095,
  -4.854356768178809,
  -4.17709228169642,
  -4.911686459770061,
  -4.591089054602736],
 'Mean Absolute Error Distribution': [-3.9206284072272664,
  -3.7924721709774807,
  -3.277684058995251,
  -3.786044304345365,
  -3.7905073858197182],
 'R² Score Distribution': [0.252690625849295,
  0.31061029356432945,
  0.3954907810104491,
  0.2789921824718288,
  0.2861536294202679],
 'Outcome Variable': 'SNAP ODD Symptoms T Score\n- rated  by Mother',
 'Number of Features': 'Selection : Mother \n Total: 502\nMother: 43\nFather: 0\nTeacher: 0\nChild: 24',
 'Feature Selection Method': 'No feature selection',

In [31]:
ml.save_cv_result_to_table(file_path_save, new_row, save=False, reduced= False, nrows2drop=2)

Column names from table :  ['Model Name', 'Cross Validation Type', 'Hyperparameters', 'Mean Squared Error', 'Root Mean Squared Error', 'Mean Absolute Error', 'R² Score', 'Outcome Variable', 'Number of Features', 'Feature Selection Method', 'Threshold Drop Row']

 NEW RESULTS TABLE (not saved):
              Model Name   Cross Validation Type                                                              Hyperparameters  Mean Squared Error  Root Mean Squared Error  Mean Absolute Error  R² Score                               Outcome Variable                                                                     Number of Features Feature Selection Method  Threshold Drop Row                                                                      Mean Squared Error Distribution                                                                  Root Mean Squared Error Distribution                                                                         Mean Absolute Error Distribution                 